apiVersion: apps/v1
kind: Deployment
metadata:
    name: pod-healthcheck-demo-app
spec:
    replicas: 5
    selector:
      matchLabels:
        app: pod-healthcheck-demo-app
    template:
      metadata:
        labels:
          app: pod-healthcheck-demo-app
      spec:
        containers:
          - name: pod-healthcheck-demo-app
            image: tusharshiledarelite1991/card
            ports:
              - containerPort: 8080