apiVersion: apps/v1
kind: Deployment
metadata:
    name: account-app-pod
spec:
    replicas: 1
    selector:
      matchLabels:
        app: account-app-pod
    template:
      metadata:
        labels:
          app: account-app-pod
      spec:
        containers:
          - name: card-app
            image: tusharshiledarelite1991/card
            ports:
              - containerPort: 8080