apiVersion: apps/v1
kind: Service
metadata:
    name: account
    labels:
      name: account-service
      app: pod-healthcheck-demo-app
spec:
    selector:
      app: account-app-pod
    ports:
      - protocol: TCP
        port: 82
        targetPort: 80

