apiVersion: v1
kind: Service
metadata:
  name: card-service
spec:
 selector:
    app.kubernetes.io/name: card-service
    ports:
      - name: card-service
        protocol: TCP
        port: 80
        targetPort: 8080
