apiVersion: v1
kind: Service
metadata:
  name: card-service
  labels:
    name: card-service
    app: card-service
spec:
  type: LoadBalancer
  selector:
    app: card-app-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80






