apiVersion: apps/v1
kind: Service
metadata:
 name: card
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-pod
  template:
    metadata:
      labels:
        app: card-app-pod
      type: LoadBalancer
    ports:
       port: 8080
       targetPort: 8080

