apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-app-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-app-pod
  template:
    metadata:
      labels:
        app: card-app-pod
    spec:
      containers:
        - name: card-app
          image: tusharshiledarelite1991/card
          ports:
            - containerPort: 8080