apiVersion: v1
kind: Service
metadata:
  name: springbootconfigmap
  labels:
    name: springbootconfigmap
    app: springbootconfigmap
spec:
  type: LoadBalancer
  selector:
    app: springbootconfigmap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

