apiVersion: apps/v1
kind: Deployment
metadata:
  name: loanapplication
spec:
  replicas: 200
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
        - name: loanapplicationcontainer
          image: tusharshiledarelite1991/loanapplication
          ports:
            - containerPort: 8090