apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: loanapplicationContainer
          image: tusharshiledarelite1991/loanapplication
          ports:
            - containerPort: 8090