kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io